---
- hosts: all
  become: true
  vars:
    arch: {"x86_64": "amd64", "aarch64": "arm64"}

  tasks:
    - name: Install dependencies
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present
        cache_valid_time: 3600

    - name: Add GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add docker repository
      apt_repository:
        repo: "deb [arch={{ arch[ansible_architecture] }}] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Install docker-ce and containerd
      apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest
        cache_valid_time: 3600

    - name: Check docker is active
      service:
        name: docker
        state: started
        enabled: yes

    - name: Ensure docker group exists
      group:
        name: docker
        state: present

    - name: Adding user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Install latest docker-compose
      block:
        - name: Determine docker-compose latest release
          become: false
          uri:
            url: "https://api.github.com/repos/docker/compose/releases/latest"
            body_format: json
          register: _docker_compose_latest
          until: _docker_compose_latest.status == 200
          retries: 2

        - name: "Install docker-compose {{ _docker_compose_latest.json.tag_name }}"
          become: true
          get_url:
            url: "https://github.com/docker/compose/releases/download/{{ _docker_compose_latest.json.tag_name }}/docker-compose-linux-{{ ansible_architecture }}"
            dest: /usr/local/bin/docker-compose
            mode: 0755
            force: true
